### ISSUE TITLE
expo prebuild issues

### ISSUE THREAD

**Issue by sergey-king** [customerio/customerio-expo-plugin#75]
`"customerio-expo-plugin": "^1.0.0-beta.8"`, `"customerio-reactnative": "^2.3.3"`,
 expo prebuild output. (Expo 47)

```
Error copying file from ./node_modules/customerio-expo-plugin/src/helpers/native-files/ios/PushService.swift to /Users/king.sergey/Documents/GitHub/ts-mobile-app/apps/native/ios/JockMKTStaging/PushService.swift:  Error: ENOENT: no such file or directory, copyfile './node_modules/customerio-expo-plugin/src/helpers/native-files/ios/PushService.swift' -> '/Users/king.sergey/Documents/GitHub/ts-mobile-app/apps/native/ios/JockMKTStaging/PushService.swift'
    at copyFileSync (node:fs:2800:3)
    at Function.copyFile (/Users/king.sergey/Documents/GitHub/ts-mobile-app/node_modules/customerio-expo-plugin/lib/commonjs/helpers/utils/fileManagement.js:47:28)
    at addPushNotificationFile (/Users/king.sergey/Documents/GitHub/ts-mobile-app/node_modules/customerio-expo-plugin/lib/commonjs/ios/withNotificationsXcodeProject.js:237:36)
    at pbxProject.<anonymous> (/Users/king.sergey/Documents/GitHub/ts-mobile-app/node_modules/customerio-expo-plugin/lib/commonjs/ios/withNotificationsXcodeProject.js:32:13)
    at pbxProject.emit (node:events:390:28)
    at pbxProject.<anonymous> (/Users/king.sergey/Documents/GitHub/ts-mobile-app/node_modules/xcode/lib/pbxProject.js:48:18)
    at ChildProcess.emit (node:events:390:28)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -2,
  syscall: 'copyfile',
  code: 'ENOENT',
  path: './node_modules/customerio-expo-plugin/src/helpers/native-files/ios/PushService.swift',
  dest: '/Users/king.sergey/Documents/GitHub/ts-mobile-app/apps/native/ios/JockMKTStaging/PushService.swift'
}
Error reading file /Users/king.sergey/Documents/GitHub/ts-mobile-app/apps/native/ios/JockMKTStaging/PushService.swift:  Error: ENOENT: no such file or directory, open '/Users/king.sergey/Documents/GitHub/ts-mobile-app/apps/native/ios/JockMKTStaging/PushService.swift'
    at Object.openSync (node:fs:585:3)
    at readFileSync (node:fs:453:35)
    at Function.readFile (/Users/king.sergey/Documents/GitHub/ts-mobile-app/node_modules/customerio-expo-plugin/lib/commonjs/helpers/utils/fileManagement.js:68:35)
    at updatePushFile (/Users/king.sergey/Documents/GitHub/ts-mobile-app/node_modules/customerio-expo-plugin/lib/commonjs/ios/withNotificationsXcodeProject.js:252:55)
    at addPushNotificationFile (/Users/king.sergey/Documents/GitHub/ts-mobile-app/node_modules/customerio-expo-plugin/lib/commonjs/ios/withNotificationsXcodeProject.js:242:3)
    at pbxProject.<anonymous> (/Users/king.sergey/Documents/GitHub/ts-mobile-app/node_modules/customerio-expo-plugin/lib/commonjs/ios/withNotificationsXcodeProject.js:32:13)
    at pbxProject.emit (node:events:390:28)
    at pbxProject.<anonymous> (/Users/king.sergey/Documents/GitHub/ts-mobile-app/node_modules/xcode/lib/pbxProject.js:48:18)
    at ChildProcess.emit (node:events:390:28)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/king.sergey/Documents/GitHub/ts-mobile-app/apps/native/ios/JockMKTStaging/PushService.swift'
}
Error copying file from ./node_modules/customerio-expo-plugin/src/helpers/native-files/ios/NotificationService-Info.plist to /Users/king.sergey/Documents/GitHub/ts-mobile-app/apps/native/ios/NotificationService/NotificationService-Info.plist:  Error: ENOENT: no such file or directory, copyfile './node_modules/customerio-expo-plugin/src/helpers/native-files/ios/NotificationService-Info.plist' -> '/Users/king.sergey/Documents/GitHub/ts-mobile-app/apps/native/ios/NotificationService/NotificationService-Info.plist'
    at copyFileSync (node:fs:2800:3)
    at Function.copyFile (/Users/king.sergey/Documents/GitHub/ts-mobile-app/node_modules/customerio-expo-plugin/lib/commonjs/helpers/utils/fileManagement.js:47:28)
    at /Users/king.sergey/Documents/GitHub/ts-mobile-app/node_modules/customerio-expo-plugin/lib/commonjs/ios/withNotificationsXcodeProject.js:116:36
    at Array.forEach (<anonymous>)
    at addRichPushXcodeProj (/Users/king.sergey/Documents/GitHub/ts-mobile-app/node_modules/customerio-expo-plugin/lib/commonjs/ios/withNotificationsXcodeProject.js:114:9)
    at async pbxProject.<anonymous> (/Users/king.sergey/Documents/GitHub/ts-mobile-app/node_modules/customerio-expo-plugin/lib/commonjs/ios/withNotificationsXcodeProject.js:35:7) {
  errno: -2,
  syscall: 'copyfile',
  code: 'ENOENT',
  path: './node_modules/customerio-expo-plugin/src/helpers/native-files/ios/NotificationService-Info.plist',
  dest: '/Users/king.sergey/Documents/GitHub/ts-mobile-app/apps/native/ios/NotificationService/NotificationService-Info.plist'
}
Error copying file from ./node_modules/customerio-expo-plugin/src/helpers/native-files/ios/NotificationService.h to /Users/king.sergey/Documents/GitHub/ts-mobile-app/apps/native/ios/NotificationService/NotificationService.h:  Error: ENOENT: no such file or directory, copyfile './node_modules/customerio-expo-plugin/src/helpers/native-files/ios/NotificationService.h' -> '/Users/king.sergey/Documents/GitHub/ts-mobile-app/apps/native/ios/NotificationService/NotificationService.h'
    at copyFileSync (node:fs:2800:3)
    at Function.copyFile (/Users/king.sergey/Documents/GitHub/ts-mobile-app/node_modules/customerio-expo-plugin/lib/commonjs/helpers/utils/fileManagement.js:47:28)
    at /Users/king.sergey/Documents/GitHub/ts-mobile-app/node_modules/customerio-expo-plugin/lib/commonjs/ios/withNotificationsXcodeProject.js:116:36
    at Array.forEach (<anonymous>)
    at addRichPushXcodeProj (/Users/king.sergey/Documents/GitHub/ts-mobile-app/node_modules/customerio-expo-plugin/lib/commonjs/ios/withNotificationsXcodeProject.js:114:9)
    at async pbxProject.<anonymous> (/Users/king.sergey/Documents/GitHub/ts-mobile-app/node_modules/customerio-expo-plugin/lib/commonjs/ios/withNotificationsXcodeProject.js:35:7) {
  errno: -2,
  syscall: 'copyfile',
  code: 'ENOENT',
  path: './node_modules/customerio-expo-plugin/src/helpers/native-files/ios/NotificationService.h',
  dest: '/Users/king.sergey/Documents/GitHub/ts-mobile-app/apps/native/ios/NotificationService/NotificationService.h'
}
Error copying file from ./node_modules/customerio-expo-plugin/src/helpers/native-files/ios/NotificationService.swift to /Users/king.sergey/Documents/GitHub/ts-mobile-app/apps/native/ios/NotificationService/NotificationService.swift:  Error: ENOENT: no such file or directory, copyfile './node_modules/customerio-expo-plugin/src/helpers/native-files/ios/NotificationService.swift' -> '/Users/king.sergey/Documents/GitHub/ts-mobile-app/apps/native/ios/NotificationService/NotificationService.swift'
    at copyFileSync (node:fs:2800:3)
    at Function.copyFile (/Users/king.sergey/Documents/GitHub/ts-mobile-app/node_modules/customerio-expo-plugin/lib/commonjs/helpers/utils/fileManagement.js:47:28)
    at /Users/king.sergey/Documents/GitHub/ts-mobile-app/node_modules/customerio-expo-plugin/lib/commonjs/ios/withNotificationsXcodeProject.js:116:36
    at Array.forEach (<anonymous>)
    at addRichPushXcodeProj (/Users/king.sergey/Documents/GitHub/ts-mobile-app/node_modules/customerio-expo-plugin/lib/commonjs/ios/withNotificationsXcodeProject.js:114:9)
    at async pbxProject.<anonymous> (/Users/king.sergey/Documents/GitHub/ts-mobile-app/node_modules/customerio-expo-plugin/lib/commonjs/ios/withNotificationsXcodeProject.js:35:7) {
  errno: -2,
  syscall: 'copyfile',
  code: 'ENOENT',
  path: './node_modules/customerio-expo-plugin/src/helpers/native-files/ios/NotificationService.swift',
  dest: '/Users/king.sergey/Documents/GitHub/ts-mobile-app/apps/native/ios/NotificationService/NotificationService.swift'
}
Error copying file from ./node_modules/customerio-expo-plugin/src/helpers/native-files/ios/NotificationService.m to /Users/king.sergey/Documents/GitHub/ts-mobile-app/apps/native/ios/NotificationService/NotificationService.m:  Error: ENOENT: no such file or directory, copyfile './node_modules/customerio-expo-plugin/src/helpers/native-files/ios/NotificationService.m' -> '/Users/king.sergey/Documents/GitHub/ts-mobile-app/apps/native/ios/NotificationService/NotificationService.m'
    at copyFileSync (node:fs:2800:3)
    at Function.copyFile (/Users/king.sergey/Documents/GitHub/ts-mobile-app/node_modules/customerio-expo-plugin/lib/commonjs/helpers/utils/fileManagement.js:47:28)
    at /Users/king.sergey/Documents/GitHub/ts-mobile-app/node_modules/customerio-expo-plugin/lib/commonjs/ios/withNotificationsXcodeProject.js:116:36
    at Array.forEach (<anonymous>)
    at addRichPushXcodeProj (/Users/king.sergey/Documents/GitHub/ts-mobile-app/node_modules/customerio-expo-plugin/lib/commonjs/ios/withNotificationsXcodeProject.js:114:9)
    at async pbxProject.<anonymous> (/Users/king.sergey/Documents/GitHub/ts-mobile-app/node_modules/customerio-expo-plugin/lib/commonjs/ios/withNotificationsXcodeProject.js:35:7) {
  errno: -2,
  syscall: 'copyfile',
  code: 'ENOENT',
  path: './node_modules/customerio-expo-plugin/src/helpers/native-files/ios/NotificationService.m',
  dest: '/Users/king.sergey/Documents/GitHub/ts-mobile-app/apps/native/ios/NotificationService/NotificationService.m'
}
Error copying file from ./node_modules/customerio-expo-plugin/src/helpers/native-files/ios/Env.swift to /Users/king.sergey/Documents/GitHub/ts-mobile-app/apps/native/ios/NotificationService/Env.swift:  Error: ENOENT: no such file or directory, copyfile './node_modules/customerio-expo-plugin/src/helpers/native-files/ios/Env.swift' -> '/Users/king.sergey/Documents/GitHub/ts-mobile-app/apps/native/ios/NotificationService/Env.swift'
    at copyFileSync (node:fs:2800:3)
    at Function.copyFile (/Users/king.sergey/Documents/GitHub/ts-mobile-app/node_modules/customerio-expo-plugin/lib/commonjs/helpers/utils/fileManagement.js:47:28)
    at /Users/king.sergey/Documents/GitHub/ts-mobile-app/node_modules/customerio-expo-plugin/lib/commonjs/ios/withNotificationsXcodeProject.js:116:36
    at Array.forEach (<anonymous>)
    at addRichPushXcodeProj (/Users/king.sergey/Documents/GitHub/ts-mobile-app/node_modules/customerio-expo-plugin/lib/commonjs/ios/withNotificationsXcodeProject.js:114:9)
    at async pbxProject.<anonymous> (/Users/king.sergey/Documents/GitHub/ts-mobile-app/node_modules/customerio-expo-plugin/lib/commonjs/ios/withNotificationsXcodeProject.js:35:7) {
  errno: -2,
  syscall: 'copyfile',
  code: 'ENOENT',
  path: './node_modules/customerio-expo-plugin/src/helpers/native-files/ios/Env.swift',
  dest: '/Users/king.sergey/Documents/GitHub/ts-mobile-app/apps/native/ios/NotificationService/Env.swift'
}
Error reading file /Users/king.sergey/Documents/GitHub/ts-mobile-app/apps/native/ios/NotificationService/NotificationService-Info.plist:  Error: ENOENT: no such file or directory, open '/Users/king.sergey/Documents/GitHub/ts-mobile-app/apps/native/ios/NotificationService/NotificationService-Info.plist'
    at Object.openSync (node:fs:585:3)
    at readFileSync (node:fs:453:35)
    at Function.readFile (/Users/king.sergey/Documents/GitHub/ts-mobile-app/node_modules/customerio-expo-plugin/lib/commonjs/helpers/utils/fileManagement.js:68:35)
    at updateNseInfoPlist (/Users/king.sergey/Documents/GitHub/ts-mobile-app/node_modules/customerio-expo-plugin/lib/commonjs/ios/withNotificationsXcodeProject.js:181:56)
    at addRichPushXcodeProj (/Users/king.sergey/Documents/GitHub/ts-mobile-app/node_modules/customerio-expo-plugin/lib/commonjs/ios/withNotificationsXcodeProject.js:121:3)
    at async pbxProject.<anonymous> (/Users/king.sergey/Documents/GitHub/ts-mobile-app/node_modules/customerio-expo-plugin/lib/commonjs/ios/withNotificationsXcodeProject.js:35:7) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/king.sergey/Documents/GitHub/ts-mobile-app/apps/native/ios/NotificationService/NotificationService-Info.plist'
}
Error reading file /Users/king.sergey/Documents/GitHub/ts-mobile-app/apps/native/ios/NotificationService/Env.swift:  Error: ENOENT: no such file or directory, open '/Users/king.sergey/Documents/GitHub/ts-mobile-app/apps/native/ios/NotificationService/Env.swift'
    at Object.openSync (node:fs:585:3)
    at readFileSync (node:fs:453:35)
    at Function.readFile (/Users/king.sergey/Documents/GitHub/ts-mobile-app/node_modules/customerio-expo-plugin/lib/commonjs/helpers/utils/fileManagement.js:68:35)
    at updateNseEnv (/Users/king.sergey/Documents/GitHub/ts-mobile-app/node_modules/customerio-expo-plugin/lib/commonjs/ios/withNotificationsXcodeProject.js:195:55)
    at addRichPushXcodeProj (/Users/king.sergey/Documents/GitHub/ts-mobile-app/node_modules/customerio-expo-plugin/lib/commonjs/ios/withNotificationsXcodeProject.js:126:3)
    at async pbxProject.<anonymous> (/Users/king.sergey/Documents/GitHub/ts-mobile-app/node_modules/customerio-expo-plugin/lib/commonjs/ios/withNotificationsXcodeProject.js:35:7) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/king.sergey/Documents/GitHub/ts-mobile-app/apps/native/ios/NotificationService/Env.swift'
}
```

**Comment by ami-aman** [comment]
Hi @sergey-king 

I apologize for the inconvenience caused. To resolve this issue, please update the `customerio-expo-plugin` to the latest version (version [ 1.0.0-beta.9](https://github.com/customerio/customerio-expo-plugin/releases/tag/1.0.0-beta.9)). This update includes the necessary fixes to address the issue you are facing. 

After updating, please let me know if the issue has been resolved for you.

**Comment by sergey-king** [comment]
Thanks @ami-aman! the issue has been resolved
